- hosts: cache
  remote_user: root  
  vars: 
    diretorio_base: /root/inf574-2018/ansible/conf

  tasks:
  - name: "setando o hostname"
    hostname:
      name: "{{ inventory_hostname }}"
    
  - name: "instalacao de pacotes"
    action: apt pkg={{item}} state=installed
    with_items:
      - wget 
      - htop 
      - iperf 
      - iptraf 
      - tcpdump 
      - ntp 
      - squid

  - name: "Habilitando NTP no boot"
    service: name=ntp enabled=yes

  - name: "Garantindo que sshd esta rodando"
    service: name=ssh state=started

  handlers:


