- hosts: ssh
  remote_user: root  
  vars: 
    diretorio_base: /root/inf574-2018/ansible/conf

  tasks:

  - name: "instalacao de pacotes"
    action: apt pkg={{item}} state=installed
    with_items:
      - wget 
      - htop 
      - iperf 
      - iptraf 
      - openssh-client 
      - tcpdump 
      - ntp 
      - rsync
      - rsyslog
      - links2

  - name: "copiando arquivo de configuracao do ntp"
    copy: src={{ item.origem }} dest={{ item.destino }} owner=root group=root mode=644
    with_items:
    - { origem: '{{diretorio_base}}/ssh/ntp.conf', destino: '/etc/ntp.conf' }

    notify: 
    - restart ntp

  - name: "copiando arquivo de configuracao do rsyslog"
    copy: src={{ item.origem }} dest={{ item.destino }} owner=root group=root mode=644
    with_items:
    - { origem: '{{diretorio_base}}/ssh/rsyslog.conf', destino: '/etc/rsyslog.conf' }
   
  - name: "copiando arquivo de exemplo em python"
    copy: src={{ item.origem }} dest={{ item.destino }} owner=root group=root mode=755
    with_items:
    - { origem: '{{diretorio_base}}/ssh/syslog1.py', destino: '/root/syslog1.py' }
    - { origem: '{{diretorio_base}}/ssh/syslog2.py', destino: '/root/syslog2.py' }

    notify: 
    - restart rsyslog

  - name: "Habilitando NTP no boot"
    service: name=ntp enabled=yes

  - name: "Habilitando rsyslog no boot"
    service: name=rsyslog enabled=yes

  - name: "Garantindo que rsyslog esta rodando"
    service: name=rsyslog state=started

  - name: "Garantindo que sshd esta rodando"
    service: name=ssh state=started

  handlers:

    - name: restart ntp
      service: name=ntp state=restarted

    - name: restart rsyslog
      service: name=rsyslog state=restarted


