- hosts: www
  remote_user: root  
  vars: 
    diretorio_base: /root/inf574-2018/ansible/conf

  tasks:
  - apk:
    update_cache: yes
    
  - name: "instalacao de pacotes"
    action: apk pkg={{item}} state=installed
    with_items:
      - wget 
      - htop 
      - iperf 
      - iptraf-ng 
      - tcpdump 
      - ntp 

  - name: "Habilitando NTP no boot"
    service: name=ntp enabled=yes

  - name: "Garantindo que sshd esta rodando"
    service: name=ssh state=started

  handlers:


